### ISSUE TITLE
Configure static IP for the server

### ISSUE THREAD

**Issue by oskarsari** [ultra-trace-systems/mascope#138]
In GitLab by @oskarsa on Dec 4, 2023, 15:38

Write a document describing how, using Linux terminal, to configure a network interface to use static IP using `nmcli`.

**Comment by oskarsari** [comment]
In GitLab by @alexei_upornikov on Dec 5, 2023, 14:11

**Static ip via netplan:**

- `sudo apt install net-tools`

- run  `ifconfig -a` ;  
  - get needed network_adapter_name, ip address, netmask, gateway_ip

- use Calculator.net to calculate Usable_Host_IP_Range from the netmask and ip:
  - Calculator.net: https://www.calculator.net/ip-subnet-calculator.html;
  - Use Network_Class=Any;
  - From calculated result, select new static ip within Usable_Host_IP_Range;
  - Use subnet mask from CIDR_Notation;

- select the new netplan config file name: 
  - list /etc/netplan folder for existing config files:
    - `ls -la /etc/netplan`
    - e.g. 50-cloud-init.yaml exists;
  - select lexically ascending name:
    - e.g. 51-eth1-static-ip.yaml
    - if no existing files, select any name as NN-blah-blah.yaml

- create a new config file as:
  - `sudo touch /etc/netplan/51-eth1-static-ip.yaml`
  - make sure *.yaml file masks are similar: `ls -la /etc/netplan`

- add the following configuration to the new yaml (mind yaml format):
```
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    <network_adapter_name>:
      dhcp4: no
      addresses: [<new_static_ip>/<CIDR_MASK>]
      gateway4: <gateway_ip>
      nameservers:
        addresses: [8.8.8.8,8.8.8.4]
```
e.g.
```
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    eth0:
      dhcp4: no
      addresses: [192.168.1.163/24]
      gateway4: 192.168.1.1
      nameservers:
        addresses: [8.8.8.8,8.8.8.4]
```
- Apply the new config:
  - `sudo netplan try`

- check the result:
  - `ip a`


**As alternative, static ip via nmcli:**

From netplan description:
  - use the network adapter name (e.g. eth1), 
  - new_ip (e.g. 192.168.1.163), 
  - CIDR mask (e.g. 24), 
  - gateway ip (e.g. 192.168.1.1):

```
sudo apt install network-manager
nmcli con add con-name "static-eth1" ifname eth1 type ethernet ip4 192.168.1.163/24 gw4 192.168.1.1
nmcli con mod "static-eth1" ipv4.dns "192.168.1.1,8.8.8.8"
nmcli con up "static-eth1" iface eth1

```
Then remove existing configurations to this adapter:
  - find existing eth1:
    - `nmcli con show`
    - check for existing configuration for the eth1:
```
      NAME         UUID                 TYPE           DEVICE
      eth1         ff9804db5-........   802-3-ethernet --
      static-eth1  a4b59cb4a-........   802-3-ethernet eth1

```
  - remove existing eth1:  `nmcli con del eth1`
